
name: Rundeck Deployment

on:
  push:
    branches:
      - main

jobs: 
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker Lint
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace aquasec/trivy:latest fs .
  
  depoy:
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Deployment process
      run: |
        ssh -o StrictHostKeyChecking=no operations@${{ secrets.SERVER_IP }} << 'EOF'
          whoami
        EOF